export default {
  WINDOW_RESIZE: 'WINDOW_RESIZE',
  ROUTE_CHANGED: 'ROUTE_CHANGED',
  PAGE_ASSETS_LOADED: 'PAGE_ASSETS_LOADED',
  PREVIEWS_LOADED: 'PREVIEWS_LOADED',
  PREVIEW_CHANGED: 'PREVIEW_CHANGED',
  MOUSEENTER_PREVIEW: 'MOUSEENTER_PREVIEW',
  MOUSELEAVE_PREVIEW: 'MOUSELEAVE_PREVIEW',
  PROJECT_IMAGES_LOADED: 'PROJECT_IMAGES_LOADED',
  PROJECT_SLIDE_CHANGED: 'PROJECT_SLIDE_CHANGED',
  TOGGLE_PROJECT_INFOS: 'TOGGLE_PROJECT_INFOS',
  MOUSEENTER_RIGHT_PROJECT: 'MOUSEENTER_RIGHT_PROJECT',
  MOUSELEAVE_RIGHT_PROJECT: 'MOUSELEAVE_RIGHT_PROJECT',
  MOUSEENTER_LEFT_PROJECT: 'MOUSEENTER_LEFT_PROJECT',
  MOUSELEAVE_LEFT_PROJECT: 'MOUSELEAVE_LEFT_PROJECT',
  INITIAL_PAGE_ASSETS_LOADED: 'INITIAL_PAGE_ASSETS_LOADED',
  LOAD_NEXT_PREVIOUS_PAGE_ASSETS: 'LOAD_NEXT_PREVIOUS_PAGE_ASSETS',
  APP_START: 'APP_START',
  LANGUAGE_CHANGED: 'LANGUAGE_CHANGED',
  ADD_TO_CANVAS: 'ADD_TO_CANVAS',
  REMOVE_FROM_CANVAS: 'REMOVE_FROM_CANVAS',
  SLIDESHOW_IS_READY: 'SLIDESHOW_IS_READY',
  NEXT_SLIDE: 'NEXT_SLIDE',
  PREVIOUS_SLIDE: 'PREVIOUS_SLIDE',
  HOME_INTERNAL_CHANGED: 'HOME_INTERNAL_CHANGED',
  BLOCK_INTERACTIVITY: 'BLOCK_INTERACTIVITY',
  UN_BLOCK_INTERACTIVITY: 'UN_BLOCK_INTERACTIVITY',
  KEYBOARD_TRIGGERED: 'KEYBOARD_TRIGGERED',
  SCROLL_TRIGGERED: 'SCROLL_TRIGGERED',

  SLIDESHOW_STATE_CHANGED: 'SLIDESHOW_STATE_CHANGED',

  SLIDESHOW: {
    BEGIN: 'BEGIN',
    END: 'END',
    MIDDLE: 'MIDDLE'
  },

  ORIENTATION: {
    LANDSCAPE: 'LANDSCAPE',
    PORTRAIT: 'PORTRAIT'
  },

  HOME: 'HOME',
  ABOUT: 'ABOUT',
  PROJECT: 'PROJECT',

  TYPE: {
    EVENT: 'EVENT',
    RETAIL: 'RETAIL'
  },

  LANG: {
    EN: 'en',
    FR: 'fr'
  },

  OPEN_PROJECTS_OVERVIEW: 'OPEN_PROJECTS_OVERVIEW',
  CLOSE_PROJECTS_OVERVIEW: 'CLOSE_PROJECTS_OVERVIEW',

  STATE: {
    PROJECTS: 'PROJECTS',
    ABOUT: 'ABOUT',
    NORMAL: 'NORMAL'
  },

  FORWARD: 'FORWARD',
  BACKWARD: 'BACKWARD',

  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  CENTER: 'CENTER',
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
  UP: 'UP',
  DOWN: 'DOWN',
  SMALL: 'SMALL',
  ESC: 'ESC',
  SPACE: 'SPACE',

  GLOBAL_MARGIN: 20,

  ENVIRONMENTS: {
    PREPROD: {
      static: 'http://localhost:3000/'
    },
    PROD: {
      static: 'http://myserver'
    }
  },

  MEDIA_GLOBAL_W: 1920,
  MEDIA_GLOBAL_H: 1280,

  MIN_MIDDLE_W: 960,
  MQ_XSMALL: 320,
  MQ_SMALL: 480,
  MQ_MEDIUM: 768,
  MQ_LARGE: 1024,
  MQ_XLARGE: 1280,
  MQ_XXLARGE: 1680
}
